CREATE TABLE [dbo].[Addresses]
(
	[Id] INT IDENTITY(1,1) CONSTRAINT PK_Addresses PRIMARY KEY CONSTRAINT NN_Id NOT NULL,
	City VARCHAR(20) CONSTRAINT NN_City NOT NULL,
	Street VARCHAR(30) CONSTRAINT NN_Street NOT NULL,
	Number VARCHAR(10) CONSTRAINT NN_Number NOT NULL
)
