CREATE TABLE [dbo].[Images]
(
	[Id] BIGINT IDENTITY(1,1) CONSTRAINT PK_Images PRIMARY KEY CONSTRAINT NN_Id NOT NULL,
	Photo VARBINARY(max) CONSTRAINT NN_Photo NOT NULL,
	[Text] VARCHAR(100),
	[Status] VARCHAR(15) CONSTRAINT NN_Status NOT NULL
)
