CREATE TABLE [dbo].[Orders]
(
	[Id] BIGINT IDENTITY(1,1) CONSTRAINT PK_Orders PRIMARY KEY CONSTRAINT NN_Id NOT NULL,
	OrderDate DATETIME2 CONSTRAINT NN_OrderDate NOT NULL,
	[Status] VARCHAR(15) CONSTRAINT NN_Status NOT NULL,
	Amount MONEY,
	AddressId INT CONSTRAINT FK_AddressesOrders FOREIGN KEY REFERENCES Addresses([Id]),
	CustomerId BIGINT CONSTRAINT FK_OrdersCustomers FOREIGN KEY REFERENCES Users([Id]) CONSTRAINT NN_CustomerId NOT NULL,
	[PhoneNumber] VARCHAR(13) NULL
)