CREATE TABLE [dbo].[Products]
(
	[Id] BIGINT IDENTITY(1,1) CONSTRAINT PK_Products PRIMARY KEY NOT NULL,
	CategoryId INT CONSTRAINT FK_ProductsCategories FOREIGN KEY REFERENCES Categories(Id) NOT NULL,
	ImageId BIGINT CONSTRAINT FK_ProductsTemplates FOREIGN KEY REFERENCES Images([Id]) NOT NULL,
	CompanyId BIGINT CONSTRAINT FK_ProductsCompanies FOREIGN KEY REFERENCES Users([Id]) NULL,
	BuyingPrice MONEY NOT NULL,
	SellingPrice MONEY NOT NULL
)
