CREATE TABLE [dbo].[Users]
(
	[Id] BIGINT IDENTITY(1,1) CONSTRAINT PK_Users PRIMARY KEY CONSTRAINT NN_Id NOT NULL,
	[Email] VARCHAR(50) NOT NULL,
	[PhoneNumber] VARCHAR(13) NULL,
	[PasswordHash] VARCHAR(100) NOT NULL,
	[Rank] VARCHAR(10) NOT NULL,
	AddressId INT NULL,
    [NormalizedUserName] VARCHAR(50) NOT NULL,
	[Name] VARCHAR(50) NOT NULL,
	[IsValid] VARCHAR(20) NULL
)
